version: "3.3"

services:
  db:
    image: mysql
    container_name: "database"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
  web:
    build: .
    container_name: "website"
    image: "car-suspension-simulation"
    ports:
      - 8080:80
    depends_on:
      - db
