version: "3.9"

services:
  db:
    platform: linux/x86_64
    container_name: "database"
    image: mysql
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
  web:
    build: .
    container_name: "website"
    ports:
      - 8080:80
    volumes:
      - ./api:/usr/src/api
      - ./client:/var/www/html
    depends_on:
      - db
